### PR TITLE
Add version of 'returns' logo with white outer outline

### PR DESCRIPTION
**Pull request by homeworkprod**
As suggested in [this comment](https://github.com/dry-python/returns/issues/195#issuecomment-609030646).

This makes it stand out on a dark background (like browsers' "Dark Mode"), too.

Outer outline vanishes on white background, so that it looks like before.

I had no SVG source of the logo available, so I made the variant based on the PNG logo. Looks surprisingly ok to me, though.

### CODE REVIEW

**Comment by orsinium** [comment]
Did you vectorize it? Can you add svg as well, please?

**Comment by orsinium** [comment]
You can take vectorized version from #1. I made it with Inkscape's "Trace Bitmap".

**Comment by homeworkprod** [comment]
@orsinium, I figured that's the way you obtained that SVG. However, it looked too different from the raster image to me, so I chose not to use it as a base.

I would have been a bit easier and cleaner to make this change starting from SVG, but since the original one (if there even was one in the first place) wasn't supplied, the PNG was the next best to one me.

**Comment by homeworkprod** [comment]
For the record, to reproduce, I just used GIMP and:
- took the PNG from the README (I think it already had an alpha channel),
- selected the background around the logo using the magic wand tool,
- inverted the selection,
- extended the selection,
- added a new layer,
- filled the selection with white,
- moved that layer to the bottom and
- exported the result as PNG again.

**Comment by proofit404** [comment]
Awesome! Thanks!

**Pull request merged**
